### PR TITLE
FIT-628: Removes preint deploy steps for Jenkins

### PR DESCRIPTION
**Pull request by edgibbs**
### JIRA Issue Link
- https://osi-cwds.atlassian.net/browse/FIT=628

### Tests
- [ ] I have included unit tests 
- [ ] I have included integration tests 
- [ ] I have included performance tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by LeonidMarushevskyi** [comment]
Jenkins retest please

**Comment by LeonidMarushevskyi** [comment]
Retest this please

**Pull request merged**
